version: '3.7'

services:
    postgres:
        image: postgres:16
        restart: always
        environment:
            POSTGRES_DB: core
            POSTGRES_USER: core_user
            POSTGRES_PASSWORD: secret
        ports:
          - "5432:5432"

    edge:
        image: edge-service:latest
        command: sh -c "uvicorn main:app --reload --host 0.0.0.0"
        build:
            context: ./edge
        env_file:
            - ./edge/.env
        ports:
          - 8001:8000
        depends_on:
          - postgres
          - accounts
          - purchases
        volumes:
          - ./edge:/app
        environment:
          - ACCOUNTS_SERVICE_URL=http://accounts:8000
          - PURCHASES_SERVICE_URL=http://purchases:8000

    accounts:
        image: accounts-service:latest
        command: sh -c "uvicorn main:app --reload --host 0.0.0.0"
        build:
            context: ./accounts
        volumes:
          - ./accounts:/app
        depends_on:
          - postgres
        environment:
          - DATABASE_URL=postgres://core_user:secret@postgres:5432/core

    purchases:
        image: purchases-service:latest
        command: sh -c "uvicorn main:app --reload --host 0.0.0.0"
        build:
            context: ./purchases
        volumes:
          - ./purchases:/app
        depends_on:
          - postgres
        environment:
          - DATABASE_URL=postgres://core_user:secret@postgres:5432/core

    frontend:
        image: node:20
        working_dir: /app
        command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
        volumes:
          - ./frontend:/app
        ports:
          - "5173:5173"
        depends_on:
          - edge
